import { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Netflix-Onedwo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
