import { ReactNode } from 'react';
import './globals.css';
import Provider from '@components/common/Provider';

export const metadata = {
  title: 'Netflix-Onedwo',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
